spring.application.name=library-management-system

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://mysql-1e8e9bfa-srisowbarniga2311-8f43.d.aivencloud.com:14296/defaultdb?useSSL=true&allowPublicKeyRetrieval=true&serverTimezone=UTC&verifyServerCertificate=false}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:avnadmin}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:AVNS_b-G0QhL5NIUcaYDwfSL}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.thymeleaf.cache=false

server.port=${PORT:8080}